### ISSUE TITLE
Influx - Unable to parse integer

### ISSUE THREAD

**Issue by VIDGuide** [sponsianus/dishy_grafana#8] opened 2022-04-02 23:30 UTC
`unable to parse 'spacex.starlink.user_terminal.status,id=ut01000000-00000000-0011e7f5 alert_mast_not_near_vertical=False,alert_motors_stuck=False,alert_roaming=False,alert_slow_ethernet_speeds=False,alert_thermal_shutdown=False,alert_thermal_throttle=False,alert_unexpected_location=False,alerts=0i,currently_obstructed=False,direction_azimuth=-175.572509765625,direction_elevation=63.66798400878906,downlink_throughput_bps=8506.048828125,fraction_obstructed=0.00021276595361996442,hardware_version=\"rev2_proto4\",obstruction_duration=0.0,obstruction_interval=nan,pop_ping_drop_rate=0.0,pop_ping_latency_ms=36.25,raw_wedges_fraction_obstructed_0=0.0,raw_wedges_fraction_obstructed_1=0.0,raw_wedges_fraction_obstructed_10=0.0,raw_wedges_fraction_obstructed_11=0.0,raw_wedges_fraction_obstructed_2=0.0,raw_wedges_fraction_obstructed_3=0.0,raw_wedges_fraction_obstructed_4=0.0,raw_wedges_fraction_obstructed_5=0.0,raw_wedges_fraction_obstructed_6=0.0,raw_wedges_fraction_obstructed_7=0.0,raw_wedges_fraction_obstructed_8=0.0,raw_wedges_fraction_obstructed_9=0.0,seconds_to_first_nonempty_slot=0.0,software_version=\"51ead67f-1bcb-4d70-8c9c-99dea649592d.uterm.release\",state=\"CONNECTED\",uplink_throughput_bps=21986.541015625,uptime=628637i,valid_s=628085.0,wedges_fraction_obstructed_0=0.0,wedges_fraction_obstructed_1=0.0,wedges_fraction_obstructed_10=0.0,wedges_fraction_obstructed_11=0.0,wedges_fraction_obstructed_2=0.0,wedges_fraction_obstructed_3=0.0,wedges_fraction_obstructed_4=0.0,wedges_fraction_obstructed_5=0.0,wedges_fraction_obstructed_6=0.0,wedges_fraction_obstructed_7=0.0,wedges_fraction_obstructed_8=0.0,wedges_fraction_obstructed_9=0.0 1648941470': invalid number`

Getting no data coming into Influx on both my old setup and a fresh brand new install of the stack. The above error is logged constantly by the grpc container. 

I suspect it's coming from:
obstruction_interval=nan

But I'm not 100% sure. Is there a way to filter that out, or at least replace nan with a 0?

**Comment by VIDGuide** [comment] 2022-04-02 23:45
Actually appears this is fixed upstream:
https://github.com/sparky8512/starlink-grpc-tools/issues/42
But this isn't the container being used in the stack.

**Comment by VIDGuide** [comment] 2022-04-02 23:59
so I'm not sure if there are any needed changes in the grpc container from the source one, but updating the compose to use:
`ghcr.io/sparky8512/starlink-grpc-tools`
instead seems to work. I'm now getting data back in Influx, and everything seems populated.

**Comment by sponsianus** [comment] 2022-04-08 22:07
Was a bit behind on updates but should be all fixed in the latest containers.

Reopen if the issue is still occurring.

**Closed by sponsianus** 2022-04-08 22:07 UTC
